knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.root_dir%/../src/Acme/DemoBundle/Resources/lib/wkhtmltopdf"
        options:    []
    image:
        enabled:    true
        binary:     "%kernel.root_dir%/../src/Acme/DemoBundle/Resources/lib/wkhtmltoimage"
        options:    []