<?php

namespace Anis\CommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFactureRepository extends EntityRepository
{

}
