<?php

namespace Anis\CommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function findAllLimited($page)
    {

        $min =($page > 0 ? ($page-1) * 10 : 0);
        //$max =($page > 0 ? $page * 10 : 10);
        $max = 10;

        $query =$this->getEntityManager()
            ->createQuery('SELECT p FROM AnisCommerceBundle:Produit p')
            ->setFirstResult($min)
            ->setMaxResults($max);

        return  $query->getResult();
    }

    public function getListBy($criteria)
    {
        $qb = $this->createQueryBuilder('i');


        foreach ($criteria as $field => $value) {
            if (!$this->getClassMetadata()->hasField($field)) {
                // Make sure we only use existing fields (avoid any injection)
                continue;
            }

            $qb ->andWhere($qb->expr()->eq('i.'.$field, ':i_'.$field))
                ->setParameter('i_'.$field, $value);
        }

        return $qb->getQuery()->getResult();
    }
}
